### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by diVineProportion** [101t/django-aio#3]
Under the windows section you have `requirements.txt` listed as `requirements.pip`

Other matter, not sure if you were going for a copy paste section with your windows and unix sections, but if you were I'd like to suggest one other change.

if you change `env/Scripts/activate` to `CALL env/Scripts/activate` it will allow you to paste the lines into a bat file and automate the whole process. currently it will stop after activating the venv

Also, what do I have to do to get this going. Everything seem to work fine, no errors, but when navigating to the 127.0.0.1:8000 I get a 404. Doesn't this have the jet dashboard admin package?

**Comment by 101t** [comment]
Hi @diVineProportion 
Thank you for your feedbacks, recently I added django-3-jet as supports django >= 3.0.x
for `README.md` I will update the readme again.
> for 127.0.0.1:8000 get 404
This is schema propose as first page should be yours! no special design or bootstrap html, howevery it made some confuse I will initial sample to avoid 404 response.

**Comment by 101t** [comment]
the changes done, please check
https://github.com/101t/django-aio#getting-started
